import { Geist } from "next/font/google";
import "@/app/globals.css";
import Link from "next/link";


const geistSans = Geist({ subsets: ["latin"] });


export const metadata = {
  title: "Mi primera app",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={geistSans.className + ' antialiased min-h-screen'}
      >
        <nav className="text-xl bg-blue-300 p-4 flex justify-between miclase">
          <Link href="/">INICIO</Link>
          <Link href="/tienda">TIENDA</Link>
          <Link href="/blog">BLOG</Link>
          <Link href="/acerca">ACERCA DE</Link>
          <Link href="/registro">REGISTRO</Link>
        </nav>
        <div className="p-4">
          {children}
        </div>
      </body>
    </html>
  )

}
