import { Geist } from "next/font/google";
import "@/app/globals.css";
import MenuLink from "@/components/MenuLink";



const geistSans = Geist({ subsets: ["latin"] });


export const metadata = {
  title: "Mi primera app",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={geistSans.className + ' antialiased min-h-screen'}
      >
        <nav className="text-xl bg-blue-300 p-4 flex justify-between miclase">
          <MenuLink href="/">INICIO</MenuLink>
          <MenuLink href="/tienda">TIENDA</MenuLink>
          <MenuLink href="/blog">BLOG</MenuLink>
          <MenuLink href="/acerca">ACERCA DE</MenuLink>
          <MenuLink href="/registro">REGISTRO</MenuLink>
        </nav>
        <div className="p-4">
          {children}
        </div>
      </body>
    </html>
  )

}
